[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./bin/thrust ./bin/rails server"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
